In [1]:
from IPython.core.display import HTML
css = open('notebook_css/style-table.css').read() + open('notebook_css/style-notebook.css').read()
HTML('<style>{}</style>'.format(css))

https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

Author: @imflash217 [September/07/2021]

# TENSORS

Tensors are specialized data structures that are very similar to arrays and matrices.

टेंसर (tensor) एक बहुत ही उत्कृष्ट डेटा स्ट्रक्चर (data structure) है जो ऐरे (array) एवं मेट्रिक्स (matrix) के समकक्ष है.

In PyTorch, we use Tensors to encode the inputs & outputs of the model as well as the model's parameters.

Tensors are similar to Numpy `ndarrays`; except that the tensors can run on GPUs or other hardware accelerators.

If fact, Tensors & Numpy arrays can share the same underlying memory, eliminating the need to copy data.

Tensors are also optimized for automatic differentiation (`Autograd`)

In [2]:
import torch
import numpy as np

## Initializing a Tensor

Tensors can be initialized in various ways:

1. Directly from data

2. From Numpy array

3. From another Tensor

4. With random or constant values

### Directly from Data

Tensors can be created directly from data. The **datatype** is automatically inferred.

In [3]:
data = [[1,2],
        [3,4],
       ]

x_data = torch.tensor(data)

x_data

tensor([[1, 2],
        [3, 4]])

### From a `numpy` array

Tensors can be created form numpy arrays & vice-versa

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

x_np

tensor([[1, 2],
        [3, 4]])

### From another Tensor

The new tensor retains the properties (shape, dtype) of the argument tensor, unless explictly overridden


In [6]:
x_ones = torch.ones_like(x_data)      ## retains the properties of x_data
print(f"Ones Tensor \n{x_ones}")

Ones Tensor 
tensor([[1, 1],
        [1, 1]])


In [7]:
x_rand = torch.rand_like(x_data, dtype=torch.float)        ## overrides the data-type of x_data
print(f"Random Tensor:\n{x_rand}")

Random Tensor:
tensor([[0.7202, 0.2566],
        [0.7286, 0.9776]])


### With `random` or `constant` values

`shape` is a tuple of tensor dimensions.

In [8]:
shape = (2,3,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tesnor:\n{rand_tensor}\n")
print(f"Ones Tensor:\n{ones_tensor}\n")
print(f"Zeros Tebsor:\n{zeros_tensor}\n")

Random Tesnor:
tensor([[0.3070, 0.7394, 0.1978],
        [0.1237, 0.5404, 0.0584]])

Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tebsor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])



## Attributes of a Tensor

Tensor attributes describe their `shape`, `dtype` (datatype) & `device` (the device they are stored on)

In [11]:
tensor = torch.rand((2,3))

print(f"""
        Shape of the tensor: {tensor.shape}\n
        Datatype of the tensor: {tensor.dtype}\n
        Device of the tensor: {tensor.device}\n
""")


        Shape of the tensor: torch.Size([2, 3])

        Datatype of the tensor: torch.float32

        Device of the tensor: cpu




## Operations on Tensor

By default Tensors are created on the CPU. We need to move the tensors to GPU using `.to()` method

NOTE: Copying large tensors across devices can be expensive in time and memory

**If you are familiar with NumPy API then the Tensor API is a breeze to use**

In [14]:
## We move our tensor to GPU if its available

if torch.cuda.is_available():
    tensor = tensor.to(device="cuda")

In [15]:
tensor.device

device(type='cpu')

### Standard numpy-like indexing and slicing

In [20]:
tensor = torch.rand((4,4))
tensor

tensor([[0.6381, 0.3969, 0.4041, 0.9981],
        [0.5977, 0.7554, 0.5118, 0.4986],
        [0.8223, 0.9271, 0.1076, 0.1209],
        [0.5900, 0.4490, 0.2765, 0.2400]])

In [21]:
print(f"First row: {tensor[0]}")

First row: tensor([0.6381, 0.3969, 0.4041, 0.9981])


In [22]:
print(f"First Column: {tensor[:, 0]}")

First Column: tensor([0.6381, 0.5977, 0.8223, 0.5900])


In [23]:
print(f"Last Column: {tensor[..., -1]}")

Last Column: tensor([0.9981, 0.4986, 0.1209, 0.2400])


In [24]:
tensor[..., 1] = 0
tensor

tensor([[0.6381, 0.0000, 0.4041, 0.9981],
        [0.5977, 0.0000, 0.5118, 0.4986],
        [0.8223, 0.0000, 0.1076, 0.1209],
        [0.5900, 0.0000, 0.2765, 0.2400]])

### Joining Tensors

You can use **`torch.cat`** to concatentate a sequence of tensors along a given dimension

**`torch.stack`** is similar but subtly different from **`torch.cat`**

In [25]:
t1 = torch.cat([tensor, tensor, tensor, tensor], dim=-1)
t1

tensor([[0.6381, 0.0000, 0.4041, 0.9981, 0.6381, 0.0000, 0.4041, 0.9981, 0.6381,
         0.0000, 0.4041, 0.9981, 0.6381, 0.0000, 0.4041, 0.9981],
        [0.5977, 0.0000, 0.5118, 0.4986, 0.5977, 0.0000, 0.5118, 0.4986, 0.5977,
         0.0000, 0.5118, 0.4986, 0.5977, 0.0000, 0.5118, 0.4986],
        [0.8223, 0.0000, 0.1076, 0.1209, 0.8223, 0.0000, 0.1076, 0.1209, 0.8223,
         0.0000, 0.1076, 0.1209, 0.8223, 0.0000, 0.1076, 0.1209],
        [0.5900, 0.0000, 0.2765, 0.2400, 0.5900, 0.0000, 0.2765, 0.2400, 0.5900,
         0.0000, 0.2765, 0.2400, 0.5900, 0.0000, 0.2765, 0.2400]])

In [28]:
tensor.shape

torch.Size([4, 4])

In [29]:
t1.shape

torch.Size([4, 16])

In [30]:
t2 = torch.stack([tensor, tensor, tensor, tensor], dim=-1)
t2

tensor([[[0.6381, 0.6381, 0.6381, 0.6381],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.4041, 0.4041, 0.4041, 0.4041],
         [0.9981, 0.9981, 0.9981, 0.9981]],

        [[0.5977, 0.5977, 0.5977, 0.5977],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.5118, 0.5118, 0.5118, 0.5118],
         [0.4986, 0.4986, 0.4986, 0.4986]],

        [[0.8223, 0.8223, 0.8223, 0.8223],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.1076, 0.1076, 0.1076, 0.1076],
         [0.1209, 0.1209, 0.1209, 0.1209]],

        [[0.5900, 0.5900, 0.5900, 0.5900],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.2765, 0.2765, 0.2765, 0.2765],
         [0.2400, 0.2400, 0.2400, 0.2400]]])

In [31]:
t2.shape

torch.Size([4, 4, 4])

### Arithmetic Operations

In [47]:
## This computes the matrix mulatiplication between two tensors
## y1, y2 & y3 will all have the same value

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[1.5666, 1.0858, 0.6889, 0.7277],
        [1.0858, 0.8678, 0.6068, 0.6138],
        [0.6889, 0.6068, 0.7024, 0.5440],
        [0.7277, 0.6138, 0.5440, 0.4822]])

In [48]:
assert torch.equal(y1, y2)
assert torch.equal(y2, y3)
assert torch.equal(y3, y1)

In [49]:
## this compute the elementwise multiplication (NOT dot product)
## z1, z2, z3 will all have the same value

z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.4072, 0.0000, 0.1633, 0.9961],
        [0.3572, 0.0000, 0.2620, 0.2486],
        [0.6762, 0.0000, 0.0116, 0.0146],
        [0.3482, 0.0000, 0.0764, 0.0576]])

In [50]:
assert torch.equal(z1, z2)
assert torch.equal(z2, z3)
assert torch.equal(z3, z1)

### Single element tensor

If we have a single element tensor, then we can access the value of the tensor by `.item()` method

In [55]:
agg = tensor.sum()
agg_item = agg.item()
print(f"agg_item = {agg_item}\nagg.dtype = {agg.dtype}\ntype(agg_item) = {type(agg_item)}")

agg_item = 5.805617332458496
agg.dtype = torch.float32
type(agg_item) = <class 'float'>


### In-place Operations

Operations that store the results into the operand itself are called **inplace ops**.

These methods are denoted by a **`_` suffix**. For ex: `x.copy_(y)`, `x.t_()` (These will change `x` itself)

NOTE: In-place ops saves memory; but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged

In [60]:
tensor = torch.rand((2,3))

print(f"{tensor}\n")
tensor.mul_(1_000)
print(f"{tensor}\n")

tensor([[0.8386, 0.5396, 0.0162],
        [0.4399, 0.3398, 0.3471]])

tensor([[838.6037, 539.5958,  16.1870],
        [439.9262, 339.7519, 347.0796]])



## Bridge with NumPy

Tensors on **CPU** and NumPy arrays can share their underlying memory locations. **Changing one will change the other**

### Tensor to NumPy array

In [66]:
t = torch.ones((5,))
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [69]:
## both share the same storage.
## so changing one will change the other

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [70]:
np.add(n, 1, out=n)

print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]
